name: Bug report
description: Report a reproducible problem
title: "bug: "
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug.
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What went wrong?
      placeholder: A clear, concise description of the bug.
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Exact steps so we can reproduce.
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      placeholder: What you expected to happen.
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
      placeholder: What actually happened.
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Versions and runtime info.
      placeholder: |
        - Package version:
        - PHP version:
        - OS:
        - Database:
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: Logs / stack traces
      description: Paste any relevant logs or stack traces.
      render: shell
    validations:
      required: false
