name: Feature request
description: Suggest an idea or enhancement
title: "feat: "
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping improve the project.
  - type: textarea
    id: problem
    attributes:
      label: Problem to solve
      description: What problem are you trying to solve?
      placeholder: I want to...
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: What would you like to see happen?
      placeholder: A clear and concise description of your idea.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      placeholder: Other approaches you considered.
    validations:
      required: false
  - type: textarea
    id: context
    attributes:
      label: Additional context
      placeholder: Any extra details, screenshots, or links.
    validations:
      required: false
